### ISSUE TITLE
Rust is not a permitted language

### ISSUE THREAD

**Issue by Zarwan** [irfansharif/qsim#10]
Greetings,

I have been reviewing the lab manual for this project and found this snippet:
<img width="719" alt="screen shot 2017-10-13 at 3 06 37 pm" src="https://user-images.githubusercontent.com/8028687/31562109-35ce5602-b028-11e7-8b86-d1d169a3fdd9.png">

Rust is not included in this list, so I believe this implementation is invalid.

**Comment by irfansharif** [comment]
![image](https://user-images.githubusercontent.com/10536690/31572483-2c80423e-b075-11e7-8db5-d8a7504c3c1d.png)
